### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by atomiciscool** [aliumutidiz/Gemini-Discord-SelfBot#1]
cant get it to wor k:sob

**Comment by atomiciscool** [comment]
> You can run it if you follow the instructions in the README file. I'm actively using the project myself.

Hey, I get a error whenever i do npm start

**Comment by atomiciscool** [comment]
well npm ERR! Missing script: "start"
npm ERR! 
npm ERR! Did you mean one of these?
npm ERR!     npm star # Mark your favorite packages
npm ERR!     npm stars # View packages marked as favorites
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run
 😭

**Comment by aliumutidiz** [comment]
> well npm ERR! Missing script: "start" npm ERR! npm ERR! Did you mean one of these? npm ERR! npm star # Mark your favorite packages npm ERR! npm stars # View packages marked as favorites npm ERR! npm ERR! To see a list of scripts, run: npm ERR! npm run 😭

I found the issue and fixed it. Thanks!
