### ISSUE TITLE
new feature 

### ISSUE THREAD

**Issue by MrshamanDev** [aliumutidiz/Gemini-Discord-SelfBot#2]
bots is amazing, but looking to get trigger message reply like i have a small server to have some fun but i want like if someone ask for particular help with a triggering message then bot reply without ping

**Comment by aliumutidiz** [comment]
I don't understand completely, can you give me an example?

**Comment by aliumutidiz** [comment]
> bots is amazing, but looking to get trigger message reply like i have a small server to have some fun but i want like if someone ask for particular help with a triggering message then bot reply without ping

All right! I've added what you requested. You can learn how to use it by looking at the admin commands in the Readme file.
